name: CI

on:
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build our docker image
      run: |
        docker build -t parla:a -f Dockerfile.a .
        docker build -t parla:b -f Dockerfile.b .
