name: CI

on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      - IMAGE_NAME=docker.pkg.github.com/ffauchille/parla-ci/parla:v1
      - CONTAINER_NAME=parla-v1
    steps:
    - uses: actions/checkout@v1
    - name: Build parla 
      run: |
       docker build -t ${{ IMAGE_NAME  }} .
       docker login docker.pkg.github.com -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_TOKEN }}
       docker push ${{ IMAGE_NAME }}
    - name: Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASSWORD }}
        script: |
          docker login docker.pkg.github.com -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_TOKEN }}
          docker stop ${{ CONTAINER_NAME }} || true
          docker rm ${{ CONTAINER_NAME }} || true
          docker pull ${{ IMAGE_NAME }}
          # Groupe SIGL: use the following line instead
          # docker run -d -p 80:80 --name ${{ CONTAINER_NAME }} ${{ IMAGE_NAME }}          
          # and comment the next one
          docker run -d --label traefik.enable=true --label traefik.docker.network=mobynet --label traefik.frontend.rule=Host:prof.arla-sigl.fr --label traefik.frontend.port=80 --name ${{ CONTAINER_NAME }} ${{ IMAGE_NAME }} 
