name: BM-CI-CI-demo

on:
  push:
    branches: 
      - bm

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build parla 
      run: |
       docker build -t docker.pkg.github.com/ffauchille/parla/parla:v1 .
       docker login docker.pkg.github.com -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_TOKEN }}
       docker push docker.pkg.github.com/ffauchille/parla/parla:v1
    - name: Deploy parla
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.WILLY_SSH_HOST }}
        username: ${{ secrets.WILLY_SSH_USER }}
        password: ${{ secrets.WILLY_SSH_PASSWORD }}
        script: |
          docker login docker.pkg.github.com -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_TOKEN }}
          cd parla
          docker-compose pull
          docker-compose down
          docker-compose up -d 
 
